export const exampleTopics: string[] = [
  "Ducks",
  "Radiohead",
  "The Smashing Pumpkins",
  "Cats",
  "Edam cheese",
  "Earth",
  "Van Halen",
  "Linus Torvalds",
  "Linux kernel",
  "Jimi Hendrix",
  "Minecraft",
  "Time travel",
  "Quantum physics",
  "Roman empire",
  "Area 51",
  "Evolution",
  "Vikings",
  "Game development",
  "Artificial intelligence",
  "Black holes",
  "X Japan",
  "Neon Genesis Evangelion",
  "Pink Floyd",
  "Metallica",
  "Angine de Poitrine",
  "Weezer",
  "Black Sabbath",
  "Bocchi the Rock",
  "88Kasyo Junrei",
  "Alexander the Great",
  "Ancient Rome",
  "Cleopatra",
  "Crime and Punishment",
  "OK Computer",
  "Paranoid (Album)",
  "South Park",
  "Freddie Mercury",
  "Nevermind (album)",
  "Panchiko",
  "Slipknot (band)",
  "Funkadelic",
  "Nirvana (band)",
  "King Crimson",
  "Alice in Chains",
  "Cyberpunk 2077",
  "Omori (video game)",
  "The Beatles",
  "My Bloody Valentine (band)",
];
