import type { Language } from "@/types";

export const exampleTopics: Record<Language, string[]> = {
  en: [
    "Ducks",
    "Radiohead",
    "The Smashing Pumpkins",
    "Cats",
    "Edam cheese",
    "Earth",
    "Van Halen",
    "Linus Torvalds",
    "Linux kernel",
    "Jimi Hendrix",
    "Minecraft",
    "Time travel",
    "Quantum physics",
    "Roman empire",
    "Area 51",
    "Evolution",
    "Vikings",
    "Game development",
    "Artificial intelligence",
    "Black holes",
    "X Japan",
    "Neon Genesis Evangelion",
    "Pink Floyd",
    "Metallica",
    "Angine de Poitrine",
    "Weezer",
    "Black Sabbath",
    "Bocchi the Rock",
    "88Kasyo Junrei",
    "Alexander the Great",
    "Ancient Rome",
    "Cleopatra",
    "Crime and Punishment",
    "OK Computer",
    "Paranoid (Album)",
    "South Park",
    "Freddie Mercury",
    "Nevermind (album)",
    "Panchiko",
    "Slipknot (band)",
    "Funkadelic",
    "Nirvana (band)",
    "King Crimson",
    "Alice in Chains",
    "Cyberpunk 2077",
    "Omori (video game)",
    "The Beatles",
    "My Bloody Valentine (band)",
    "Julius Ceasar",
    "Nikola Tesla",
    "Marie Curie",
    "World War II",
    "The Cold War",
    "String theory",
    "Theory of relativity",
    "Time dilation",
    "George Orwell",
    "Franz Kafka",
    "Stoicism",
    "Absurdism",
    "Nihilism",
    "Apollo 11",
    "SCP Foundation",
  ],
  pl: [
    "Radiohead",
    "The Smashing Pumpkins",
    "Ser edamski",
    "Ziemia",
    "Van Halen",
    "Jimi Hendrix",
    "Linus Torvalds",
    "Linux (jądro)",
    "Minecraft",
    "Podróżowanie w czasie",
    "Ewolucja",
    "Starożytny Egipt",
    "Starożytny Rzym",
    "Sztuczna Inteligencja",
    "X Japan",
    "Pink Floyd",
    "Metallica",
    "Weezer",
    "Black Sabbath",
    "Neon Genesis Evangelion",
    "Aleksander Macedoński",
    "OK Computer",
    "Nirvana",
    "Cyberpunk 2077",
    "Alice in Chains",
    "The Beatles",
    "Juliusz Słowacki",
    "Adam Mickiewicz",
    "Maria Skłodowska-Curie",
    "II wojna światowa",
    "Zimna wojna",
    "Fiodor Dostojewski",
    "Freddie Mercury",
    "Stoicyzm",
    "Absurdyzm",
    "Nihilizm",
    "Dylatacja czasu",
    "Apollo 11",
  ],
};
